# Generated by Django 3.0.8 on 2021-01-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210122_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirmpw',
            field=models.CharField(default=(), max_length=100),
        ),
    ]
